spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/cdas_db

spring.datasource.username=KPRx3NGMCWm2SYi.root

spring.datasource.password=0Ra3HLwaAccudJeE

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=8080